### ISSUE TITLE
please add support for 8 bit lcd

### ISSUE THREAD

**Issue by OprekersMania** [Bodmer/TFT_HX8357#11]
Hello Mr Bodmer.

I want to use this lib for my 8bit ili9481 and ili9486 lcd from broken chinaphones.

I use diy UNO shield for ILI9481 that use PORTD pin D0 to D7 for lcd data line.
PORTC pin A0=RD, A1=WR, A2=RS, A3=CS, A4=RST.

And i use to MEGA diy shield for ILI9486, that use PORTA for the 8 bit lcd dataline.
RS=38, CS=40, WR=38, RST=41, RD=42

with that combination pin for lcd data, i know that serial function cannot be used,but for this im already not need.

Can you make/give me a test branch or solution for shield that i use to make it works with your lib code with arduino UNO/MEGA that use 8 bit lcd, because i try to change itself with not good result.

Very tanks for your response.

Sorry for my bad english.

**Comment by Bodmer** [comment]
At the moment I do not have the free time to do this, sorry!
