### ISSUE TITLE
New Function - drawLeftString

### ISSUE THREAD

**Issue by erkanokman-zz** [Bodmer/TFT_HX8357#13]
*-*-*-*-*-* Keywords.txt *-*-*-*-*-*
drawLeftString		KEYWORD2

*-*-*-*-*-* TFT_HX8357.h *-*-*-*-*-*
drawLeftString(char *string, int16_t dX, int16_t poY, int16_t font),

*-*-*-*-*-* TFT_HX8357.cpp   *-*-*-*-*-*
/***************************************************************************************
** Function name:           drawLeftString
** Descriptions:            draw string left justified to dX
***************************************************************************************/
int16_t TFT_HX8357::drawLeftString(char *string, int16_t dX, int16_t poY, int16_t font)
{
  byte tempdatum = textdatum;
  int16_t sumX = 0;
  textdatum = TL_DATUM;
  sumX = drawString(string, dX, poY, font);
  textdatum = tempdatum;
  return sumX;
}

**Comment by Bodmer** [comment]
Using Right and Centre String are deprecated approaches. The formatting is now dictated by setTextDatum() see examples. By default the drawString function is left justified.
