### ISSUE TITLE
strange pixel on the display during running on Atmega2560

### ISSUE THREAD

**Issue by mobifu1** [Bodmer/TFT_HX8357#14]
you can load my using code for testing:
https://github.com/mobifu1/arduino_pa_controller

After 1 minute of running, the software produce many strange colored pixel.
The pixel position on the display looks like a random process.
maybe you can reproduce the error.
regards Mobifu1

**Comment by Bodmer** [comment]
I suspect you are using the HX8357B controller. This version of the controller appears to have a silicon level bug in the controller that generates spurious pixels. I expect that is why there is a HX8357C controller as that one does not exhibit the same problem.

Unfortunately there is nothing I can do to fix this (I have spent a long time investigating this!) except suggest that the complete screen is redrawn occasionally to wipe out the odd pixels.

**Comment by mobifu1** [comment]
Hello Bodmer,
thank you for the information and your work, yes the board was cheap, thats the problem :-)
regards from Hamburg Mobifu1

 

 

aajahnke@aol.com

**Comment by Bodmer** [comment]
The 3" HX8357C based display is also cheap for it's size and works really well. I will update the ReadMe to notify users of this issue. Thanks.
