### ISSUE TITLE
Possible bug in drawChar when textsize = 3

### ISSUE THREAD

**Issue by g8ecj** [Bodmer/TFT_HX8357#15]
Noticed a potential for a lockup if textsize == 3 in drawChar.
Line 2202 assumes textsize x textsize is multiple of 4 when 3*3 obviously isn't!!
Should be handled as per lines 2241-2 so tnp is checked in blocks of 4 but  only if > 3 i.e.
     while(tnp>3){ tnp-=4; WR_STB; WR_STB; WR_STB; WR_STB; }
     while(tnp)  { tnp--;  WR_STB;}
unless of course I've missed something (very likely!!)

**Comment by Bodmer** [comment]
Well spotted, that is a bug. I will fix it. Thanks.

**Comment by Bodmer** [comment]
Bug corrected. Thanks.
