### ISSUE TITLE
HX8357C on an ESP32

### ISSUE THREAD

**Issue by holgerlembke** [Bodmer/TFT_HX8357#20]
Hi.

I have one of those HX8357C 480x320 16-bit-parallel TFT displays marked as HX8357C that are Mega2560 compatible.

As far as I see, there seems no way to connect them to a ESP32. Right?

Any chance to shift out the 16 bit data via two 74x595?

I have no clue about driving tft displays...

Thanks!

**Comment by Bodmer** [comment]
In principle using shift registers is possible and this is the approach that is used in some RPi displays.  I have adapted the TFT_eSPI library to handle 8 bit displays but the HX8357C is not a supported display.
