### ISSUE TITLE
Greek characters

### ISSUE THREAD

**Issue by asvoulis** [Bodmer/TFT_HX8357#21]
I' m trying to print in the lcd greek characters but i cant find the way. The lcd uses an ILI9481 chipset and is the one for arduino mega board.
my combination is like this https://www.aliexpress.com/store/product/Free-shipping-3-2-inch-TFT-LCD-screen-module-Ultra-HD-320X480-for-Arduino-MEGA-2560/1266255_32259156914.html
thanks in advance

**Comment by Bodmer** [comment]
The library does not support extended character sets so unfortunately greek characters are not available.
