### ISSUE TITLE
Greek characters on 3,5 TFT / LCD mcufriend screen

### ISSUE THREAD

**Issue by gkevasi** [Bodmer/TFT_HX8357#22]
Hello
I try to display Greek characters on the screen. 
Is there any way?
Thanks in advance

**Comment by Bodmer** [comment]
The included fonts do not have Greek characters.. It would be possible to add new fonts in the Adafruit free font format, Adafruit provide a utility for this but it runs under Linux:

https://github.com/adafruit/Adafruit-GFX-Library/tree/master/fontconvert

**Comment by gkevasi** [comment]
Very fast responce.
Thanks
