### ISSUE TITLE
drawEllipse()/fillEllipse() are flawed on radius >175px

### ISSUE THREAD

**Issue by the-vindicar** [Bodmer/TFT_HX8357#24]
On photo there are two ellipses draw: blue one with rx=175 and ry=50, and red one with rx=200 and ry=50. As you can see, the red one is bugged.
![img_20180727_204410](https://user-images.githubusercontent.com/2130028/43340051-c1e14346-91e3-11e8-94ef-58429f720395.jpg)

Debug output shows that value of rx2 on line 563 computes as rx2=-25536 instead of 40000 despite using int32_t for the variable. As far as I understand it, the multiplication is performed within int16_t domain (which results in an overflow) and result is converted into int32_t.

Using the following calculation fixes the problem:
```
int32_t rx2 = ((int32_t)rx)*((int32_t)rx);
int32_t ry2 = ((int32_t)ry)*((int32_t)ry);
```

Sadly, I don't quite understand how to make a pull-request, so I post the change here.

**Comment by the-vindicar** [comment]
Sketch to reproduce the bug above:
```
#include <TFT_HX8357.h>
TFT_HX8357 tft = TFT_HX8357();

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  tft.begin();
  tft.setRotation(1);
  tft.fillScreen(TFT_BLACK);
  tft.drawEllipse(175, 50, 175, 50, TFT_BLUE);
  tft.drawEllipse(200, 50, 200, 50, TFT_RED);

  tft.setTextColor(TFT_WHITE);
  tft.setTextSize(3);
  tft.print(tft.width());
  tft.print("x");
  tft.print(tft.height());
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

**Comment by Bodmer** [comment]
Thanks for reporting this and identifying the cause, I have updated the code.
