### ISSUE TITLE
Esp8266

### ISSUE THREAD

**Issue by kuzmanzs** [Bodmer/TFT_HX8357#25]
Hi,

could it operate with Wemos mini/ESP8266 or it has too few legs?

**Comment by Bodmer** [comment]
Yes, it has enough pins for SPI displays, but not for parallel ones.

You need to use the TFT_eSPI library.

Check the User_Setup.h file which tells you which pins are needed.

**Comment by kuzmanzs** [comment]
Thanks your reply.

I will check it.
