### ISSUE TITLE
How do I clear the screen(Is there any function for it?)

### ISSUE THREAD

**Issue by someGuy332** [Bodmer/TFT_HX8357#29]

**Comment by rafik73github** [comment]
tft.fillScreen(color);

**Comment by someGuy332** [comment]
> tft.fillScreen(color);

it doesn't really work for me.....
tft.setCursor(80,100);
tft.setTextColor(WHITE, BLACK);
tft.setTextSize(13);
tft.print(75);
tft.fillScreen(BLACK);

this is my code but nothing happens :(

**Comment by rafik73github** [comment]
Do you initialize tft?
tft.init();
try 
tft.fillScreen(TFT_BLACK);
