### ISSUE TITLE
Ili9481 text mirrored

### ISSUE THREAD

**Issue by Fallen2504** [Bodmer/TFT_HX8357#31]
Hi,
I am using a Ili9481 with arduino mega but my text is mirrored . Can you help fix it please?

**Comment by Bodmer** [comment]
Have you  selected the correct display by editing[ the setup file](https://github.com/Bodmer/TFT_HX8357/blob/master/User_Setup.h#L9) in the library folder?

**Comment by Fallen2504** [comment]
I dont know how to do it.

**Comment by Fallen2504** [comment]
Where can i find the setup file and how to select correct display?

**Comment by Fallen2504** [comment]
I dont know what to edit in setup file and where to get setup file from?

**Comment by Bodmer** [comment]
See #32
