### ISSUE TITLE
ILI9481 MIRRORED TEXT

### ISSUE THREAD

**Issue by Fallen2504** [Bodmer/TFT_HX8357#32]
Hi ,
I am using ili9481 and arduino mega but my output text us mirrored. Can you please tell me what changes i have to make in setup file to fix this and where to get setup file from.

**Comment by Bodmer** [comment]
The setup file is already in the TFT_HX8357 library folder you are using. Open it in a text editor and change driver selected. Comment out all but one using // at start of line. Remove // from the start of the line for the driver you want. Save the file, recompile sketch and upload.
