### ISSUE TITLE
Clearing screen in tft_hx8357

### ISSUE THREAD

**Issue by Fallen2504** [Bodmer/TFT_HX8357#37]
Hi
What is the command for clearing screen for tft.
I tried  fillScreen(color)  but i deletes every thing from screen. Even what i have typed in void setup.

**Comment by Bodmer** [comment]
It appears you need to learn how the TFT screens can be used. The TFT_HX8357 library is based on the Adafruit_GFX library so I suggect you read this [tutorial](https://learn.adafruit.com/adafruit-gfx-graphics-library/overview). I do not have the time to teach users basic stuff that you should be able to work out by looking at the examples.
