### ISSUE TITLE
Adafruit Grand Central M4 SAMD

### ISSUE THREAD

**Issue by Grover-Torbel** [Bodmer/TFT_HX8357#48]
Is there any possibility that compatibility with the Arduino Grand Central M4 will be available?  It’s a very fast board and has proven compatible with every other Arduino Mega focused library I’ve tried, but it is M4 based with SAMD.  https://www.adafruit.com/product/4064

**Comment by Bodmer** [comment]
The library is for Mega boards only. It uses low level hardware specific register writes to gain a performance advantage. Other processors will not work.
