### ISSUE TITLE
MEGA support

### ISSUE THREAD

**Issue by japina** [Bodmer/TFT_HX8357#5]
Hi,

according to README the libraries should work with MEGA, but the Due is ARM based board (Cortex M3) and MEGA is AVR based, so (I guess) this difference brings some errors (missing REG_PIOC_CODR). 
Do you know anything about it?

Thanks.

**Comment by Bodmer** [comment]
I do not understand the question, so in the following I am guessing what you may need to know or understand.

I have 2 libraries in my repository, one for the Mega (called TFT_HX8357) and one for the Due (called TFT_HX8357_Due). You need to use the library and examples (these have the correct constructor) according to the hardware you have. Don't forget to set the correct target board in the IDE.
